############################
## CHANGE THESE
############################

baseURL: 'http://anton.xyz'
title: 'K K  K K'

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'et-ee'


